sudo: true
language: node_js
notifications:
  email: true
node_js:
  - '6'
install:
- sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update
- sudo apt-get install yarn
- yarn install
branches:
  except:
    - /^v\d+\.\d+\.\d+.*/
    - gh-pages
after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
    eval 'npm run semantic-release';
  fi
